---
apiVersion: v1
kind: Service
metadata:
  name: opennms
  labels:
    app: opennms
spec:
  selector:
    app: opennms
  type: LoadBalancer
  ports:
    - port: 8980
      targetPort: 8980
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  clusterIP: None
  ports:
    - port: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:9
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: opennms
  labels:
    app: opennms
spec:
  containers:
    - name: opennms
      image: agalue/opennms-ui-openjdk:22.0.1
      env:
        - name: POSTGRES_HOST
          value: "postgres.default.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      ports:
        - containerPort: 8980

