version: '2'

services:

  postgres_server:
    image: postgres:9
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - opennms_db:/var/lib/postgresql/data

  opennms_server:
    image: agalue/opennms
    environment:
      - POSTGRES_HOST=postgres_server
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8980:8980"
    depends_on:
      - postgres
    volumes:
      - opennms_etc:/opt/opennms/etc
      - opennms_share:/opt/opennms/share
      - opennms_logs:/opt/opennms/logs
      - postgres:postgres_server
