version: '2'
services:
  postgres:
    image: postgres
    container_name: postgres_server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
  opennms:
    image: agalue/opennms
    container_name: opennms_server
    environment:
      - POSTGRES_HOST=postgres_server
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8981:8980"
    depends_on:
      - "postgres"
    links:
      - postgres:postgres_server
